### PR TITLE
Consistently assign NUM_THREADS a string of only decimal digits

### PR DESCRIPTION
**Pull request by jfingerh**
Then use -j$NUM_THREADS wherever the value is used as an argument to
the make command.

### CODE REVIEW

**Comment by jfingerh** [comment]
If this change is preferable to the one given in PR https://github.com/ipdk-io/ipdk/pull/27, please merge this one and close that one.

**Comment by jfingerh** [comment]
It appears that similar code exists in other ipdk-related repos, too, e.g. here: https://github.com/ipdk-io/ovs/blob/ovs-with-p4/os_ver_details.sh#L44-L59

Thankfully at least that occurrence of that similar bash code and the one in this repo appear to not depend directly upon each other.

**Review by mestery — APPROVED** [review]
This looks good, but it would be even better if you could use the DCO [1]. If you could, can you redo your commit with `-s` added and force push to this branch? Something like this:

`git commit --amend -s`

[1] https://wiki.linuxfoundation.org/dco

**Comment by jafingerhut** [comment]
I appreciate the help in how to contribute PRs to this repo cleanly.  I am not sure how much trouble it is to follow those instructions (perhaps it is quick and easy, and I have not determined that yet), but I'm also happy if someone else independently fixes these issues before I figure that out.

**Comment by mestery** [comment]
@jafingerhut Looks like there are merge conflicts which need resolving anyways. I can fix those later this afternoon and merge this if you want, let me know. I can also add the DCO if you want.

**Comment by mestery** [comment]
Closing as #86 cleaned the rest of this up, along with ipdk-io/ovs#17

**Comment by jfingerh** [comment]
Thanks for doing the fixes!  Apologies for not following through on the rest of the work needed to get the fixes in, but glad you were able to.

**Pull request closed without merging**
