### PR TITLE
Always assign variable NUM_THREADS a string beginning with "-j"

### PR DESCRIPTION
**Pull request by jfingerh**
since it is used in commands like "make $NUM_THREADS"

### CODE REVIEW

**Comment by mestery** [comment]
Hmmmmm .... I'd almost rather do the reverse here and assign it to something (even 1), and then in the `make` commands, put `make -j${NUM_THREAD}`. Thoughts?

**Comment by jfingerh** [comment]
I'm happy doing it either way.  It is the mix of sometimes one way, sometimes the other that we have now that we should definitely avoid.  I can create another PR that leaves NUM_THREADS string without the `-j` prefix in all cases, and update everywhere it is used, and people can pick their favorite.

**Comment by vsureshkumarp** [comment]
@mestery, @jfingerh 

I think "NUM_CORES" parameter value should come from either one of the following
    - User configures by using the environment variable or 
    - Derived from the system cores if user not specified
The parameter NUM_THREADS value derived from the NUM_CORES and not expected from the user configured values.

The parameter "NUM_THREADS" value populated 
   -  NUM_THREADS = "-j{NUM_THREADs} if NUM_CORES is greater than 4. or
   -  NUM_THREADS = ""

No need of specifying the "-j 1" option for non parallel compilation/build procedure I feel.

**Comment by mestery** [comment]
Lets go with #33 in lieu of this one.

**Pull request closed without merging**
