### PR TITLE
README: Make build instructions explicit

### PR DESCRIPTION
**Pull request by mestery**
This makes the IPDK build instructions much clearer by putting a note in
the top-level README.md file on how to perform a build.

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by mestery** [comment]
@jafingerhut Can you review this one, per your Slack comments? Thanks!

**Comment by mestery** [comment]
@stolsma can you review this one?

**Comment by stolsma** [comment]
@mestery LGTM! Found no nits...

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
