### PR TITLE
GitHub actions to build storage docker images and push to GHCR.io

### PR DESCRIPTION
**Pull request by mgaravin**

### CODE REVIEW

**Review by intelfisz — APPROVED** [review]
Do we need to push 2 images with different tags instead of just one?

**Review by dandaly — COMMENTED** [review]
Hi,
  Can you rename the 'ipu-storage-container' the 'infra-storage-container' or 'initiator-storage-container'?  I think this container could run on a host or on a DPU.

**Comment by mgaravin** [comment]
> Do we need to push 2 images with different tags instead of just one?

The first one is based on commit hash and second one is "main" which is kind of floating tag, will be pointing to latest always.

**Comment by mgaravin** [comment]
> Hi, Can you rename the 'ipu-storage-container' the 'infra-storage-container' or 'initiator-storage-container'? I think this container could run on a host or on a DPU.

Hi Dan

Let me check with Filip and team, as i used the names based on https://github.com/ipdk-io/ipdk/blob/main/build/storage/scripts/build_container.sh, thanks!

**Pull request merged**
