### PR TITLE
Add SSHTerminal

### PR DESCRIPTION
**Pull request by rilnickx**
An SSHTerminal class was implemented to provide a possibility to execute commands on the SSH server. This will be used in future test development. In addition folders and README.md files were added for future test development purposes.

### CODE REVIEW

**Review by artek-koltun — APPROVED** [review]
Let's add `requirements.txt` in a next patch

**Review by artek-koltun — CHANGES_REQUESTED** [review]
Please add the headers to all source files
```
# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
```

**Review by intelfisz — APPROVED** [review]

**Review by intelfisz — COMMENTED** [review]
Do you follow any specific comment style guide?
It should be consistent across all code you are contributing.
Also, I don't think you should come up with own comment syntax/convention but rather follow some syntax for a purpose -like Sphinx/Doxygen integration or similar.

**Review by artek-koltun — APPROVED** [review]
Got OSPD approval.

**Pull request merged**
